import { useMemo, useState } from 'react';

const lightness = [18, 26, 34, 42, 50, 58, 66, 76];
const hslToHex = (h, s, l) => { s /= 100; l /= 100; const c = (1 - Math.abs(2 * l - 1)) * s; const x = c * (1 - Math.abs((h / 60 % 2) - 1)); const [r,g,b] = h < 60 ? [c,x,0] : h < 120 ? [x,c,0] : h < 180 ? [0,c,x] : h < 240 ? [0,x,c] : h < 300 ? [x,0,c] : [c,0,x]; const m = l - c / 2; return `#${[r,g,b].map(v => Math.round((v+m)*255).toString(16).padStart(2,'0')).join('')}`; };
const colors = Array.from({ length: 16 }, (_, i) => i * 22.5).flatMap(hue => lightness.map((value, shade) => ({ hue, shade, hsl: `hsl(${hue}, 82%, ${value}%)`, hex: hslToHex(hue, 82, value) })));

export default function App() {
  const [selected, setSelected] = useState(colors[35]);
  const [hexInput, setHexInput] = useState(colors[35].hex.slice(1));
  const [copied, setCopied] = useState(false);
  const rgb = useMemo(() => { const n = Number.parseInt(selected.hex.slice(1), 16); return { r: n >> 16 & 255, g: n >> 8 & 255, b: n & 255 }; }, [selected]);
  const choose = color => { setSelected(color); setHexInput(color.hex.slice(1)); setCopied(false); };
  const applyHex = () => { const value = hexInput.trim().replace(/^#/, '').toLowerCase(); if (/^[0-9a-f]{6}$/.test(value)) setSelected(value === selected.hex.slice(1) ? selected : { ...selected, hex: `#${value}` }); else setHexInput(selected.hex.slice(1)); };
  const copyHex = async () => { await navigator.clipboard.writeText(selected.hex); setCopied(true); setTimeout(() => setCopied(false), 1500); };
  return <main className="page-shell"><section className="picker-card" aria-label="128 color picker"><div className="intro"><div className="eyebrow"><span className="eyebrow-dot"/>Color studio</div><h1>Find your <em>color.</em></h1><p>Explore a curated palette of 128 vivid shades, then copy the exact value you need.</p></div><div className="workspace"><div className="palette-panel"><div className="panel-heading"><div><h2>All colors</h2><span>16 hues · 8 shades</span></div><span className="count-badge">128</span></div><div className="swatch-grid" role="list" aria-label="Available colors">{colors.map(color => <button key={color.hex} className={`swatch${selected.hex === color.hex ? ' selected' : ''}`} style={{ '--swatch': color.hsl }} aria-label={`Choose ${color.hex}`} aria-pressed={selected.hex === color.hex} onClick={() => choose(color)}>{selected.hex === color.hex && <span className="check">✓</span>}</button>)}</div><div className="legend"><span className="legend-line"/>Click a swatch to select</div></div><aside className="details-panel"><div className="preview" style={{ '--selected': selected.hex }}><span>Selected color</span><strong>{selected.hex}</strong></div><div className="details-content"><label className="field-label" htmlFor="hex-value">HEX value</label><div className="hex-entry"><span>#</span><input id="hex-value" value={hexInput} maxLength="6" onChange={e => setHexInput(e.target.value)} onBlur={applyHex} onKeyDown={e => e.key === 'Enter' && applyHex()} aria-label="HEX color value"/><button className="apply-button" onClick={applyHex}>Apply</button></div><div className="value-list"><div className="value-row"><span>RGB</span><code>{rgb.r}, {rgb.g}, {rgb.b}</code></div><div className="value-row"><span>HSL</span><code>hsl({Math.round(selected.hue)}, 82%, {lightness[selected.shade]}%)</code></div></div><button className="copy-button" onClick={copyHex}><span>{copied ? '✓' : '⧉'}</span>{copied ? 'Copied to clipboard' : 'Copy HEX value'}</button></div></aside></div></section></main>;
}
