<script setup>
import { computed, ref } from 'vue';
const lightness = [18, 26, 34, 42, 50, 58, 66, 76];
const hslToHex = (h, s, l) => { s /= 100; l /= 100; const c = (1 - Math.abs(2 * l - 1)) * s; const x = c * (1 - Math.abs((h / 60 % 2) - 1)); const [r,g,b] = h < 60 ? [c,x,0] : h < 120 ? [x,c,0] : h < 180 ? [0,c,x] : h < 240 ? [0,x,c] : h < 300 ? [x,0,c] : [c,0,x]; const m = l - c / 2; return `#${[r,g,b].map(v => Math.round((v+m)*255).toString(16).padStart(2,'0')).join('')}`; };
const colors = Array.from({ length: 16 }, (_, i) => i * 22.5).flatMap(hue => lightness.map((value, shade) => ({ hue, shade, hsl: `hsl(${hue}, 82%, ${value}%)`, hex: hslToHex(hue, 82, value) })));
const selected = ref(colors[35]); const hexInput = ref(selected.value.hex.slice(1)); const copied = ref(false);
const selectedRgb = computed(() => { const n = Number.parseInt(selected.value.hex.slice(1), 16); return { r: n >> 16 & 255, g: n >> 8 & 255, b: n & 255 }; });
const selectedHsl = computed(() => `hsl(${Math.round(selected.value.hue)}, 82%, ${lightness[selected.value.shade]}%)`);
const choose = color => { selected.value = color; hexInput.value = color.hex.slice(1); copied.value = false; };
const applyHex = () => { const value = hexInput.value.trim().replace(/^#/, '').toLowerCase(); if (/^[0-9a-f]{6}$/.test(value)) selected.value = { ...selected.value, hex: `#${value}` }; else hexInput.value = selected.value.hex.slice(1); };
const copyHex = async () => { await navigator.clipboard.writeText(selected.value.hex); copied.value = true; setTimeout(() => copied.value = false, 1500); };
</script>
<template><main class="page-shell"><section class="picker-card" aria-label="128 color picker"><div class="intro"><div class="eyebrow"><span class="eyebrow-dot"></span>Color studio</div><h1>Find your <em>color.</em></h1><p>Explore a curated palette of 128 vivid shades, then copy the exact value you need.</p></div><div class="workspace"><div class="palette-panel"><div class="panel-heading"><div><h2>All colors</h2><span>16 hues · 8 shades</span></div><span class="count-badge">128</span></div><div class="swatch-grid" role="list" aria-label="Available colors"><button v-for="color in colors" :key="color.hex" class="swatch" :class="{ selected: selected.hex === color.hex }" :style="{ '--swatch': color.hsl }" :aria-label="`Choose ${color.hex}`" :aria-pressed="selected.hex === color.hex" @click="choose(color)"><span v-if="selected.hex === color.hex" class="check">✓</span></button></div><div class="legend"><span class="legend-line"></span>Click a swatch to select</div></div><aside class="details-panel"><div class="preview" :style="{ '--selected': selected.hex }"><span>Selected color</span><strong>{{ selected.hex }}</strong></div><div class="details-content"><label class="field-label" for="hex-value">HEX value</label><div class="hex-entry"><span>#</span><input id="hex-value" v-model="hexInput" maxlength="6" @change="applyHex" @keyup.enter="applyHex" aria-label="HEX color value"><button class="apply-button" @click="applyHex">Apply</button></div><div class="value-list"><div class="value-row"><span>RGB</span><code>{{ selectedRgb.r }}, {{ selectedRgb.g }}, {{ selectedRgb.b }}</code></div><div class="value-row"><span>HSL</span><code>{{ selectedHsl }}</code></div></div><button class="copy-button" @click="copyHex"><span>{{ copied ? '✓' : '⧉' }}</span>{{ copied ? 'Copied to clipboard' : 'Copy HEX value' }}</button></div></aside></div></section></main></template>
